# Generated by Django 5.2 on 2025-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('runurgencias', 'Run Urgencias'), ('runcliente', 'Run Cliente'), ('simulate', 'Simulate Multi Salas')], max_length=20)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('args', models.JSONField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
